Moved all dmenu scripts into a single script. Removed dependence on ~/.dmenurc in a bunch of places, and removed a bunch of old hardcoded stuff

diff --git a/x11/bin/block b/x11/bin/block
--- a/x11/bin/block
+++ b/x11/bin/block
@@ -1,5 +1,12 @@
 #!/usr/bin/env bash
 
+for i in scrot convert i3lock; do
+  if ! hash $i; then
+    echo "Not all required executables are installed! Please install $i"
+    exit 1
+  fi
+done
+
 FILE="/tmp/screenshot.png"
 BLUR="/tmp/screenshotblur.png"
 if [ -f $FILE ];
